version: '3.1'
services:
  db:
    image: postgres
    container_name: eventoapp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sg
      POSTGRES_DB: eventoapp
    ports:
      - "3309:5432"
    volumes:
      - eventoapp:/var/lib/postgres

volumes:
  eventoapp: